const posts = [
  {
    id: 1,
    titulo: 'GESTIÓN DE OBRAS PUBLICAS',
    descripcion: '16 de mayo de 2025 / No Comments',
    descripcion2: 'La gestión de obras públicas implica planificar, ejecutar y supervisar proyectos de infraestructura que mejoran la calidad de vida de la comunidad. Incluye etapas clave...',
    descripcionExtra: 'para garantizar que se cumplan los estándares de calidad, seguridad y sostenibilidad. Los profesionales en este campo deben coordinar recursos, gestionar presupuestos y cumplir con normativas legales.',
    imagen: '/img/digital1.png',
    colorFondo: '#e3f2fd',
    colorTexto: '#1565c0',
    colorBorde: '#1976d2',
    categoria: 'educacion'
  },
  {
    id: 2,
    titulo: 'LA GESTIÓN EFECTIVA DE ALMACENES',
    descripcion: '16 de mayo de 2025 / No Comments',
    descripcion2: 'La gestión efectiva de almacenes abarca la planificación, control y supervisión de inventarios para asegurar un flujo eficiente de productos desde la recepción hasta el...',
    descripcionExtra: 'para garantizar que se cumplan los estándares de calidad, seguridad y sostenibilidad. Los profesionales en este campo deben coordinar recursos, gestionar presupuestos y cumplir con normativas legales.',
    imagen: '/img/digital1.png',
    colorFondo: '#fff3e0',
    colorTexto: '#ef6c00',
    colorBorde: '#ff9800',
    categoria: 'innovacion'
  },
  {
    id: 3,
    titulo: '¿Cómo impacta el nuevo reglamento del SBN en la gestión pública?',
    descripcion: '16 de mayo de 2025 / No Comments',
    descripcion2: 'El nuevo reglamento de la Superintendencia Nacional de Bienes Estatales (SBN) en Perú introduce modificaciones significativas en la gestión de los bienes estatales, con el objetivo de...',
    descripcionExtra: 'para garantizar que se cumplan los estándares de calidad, seguridad y sostenibilidad. Los profesionales en este campo deben coordinar recursos, gestionar presupuestos y cumplir con normativas legales.',
    imagen: '/img/digital1.png',
    colorFondo: '#e8f5e9',
    colorTexto: '#2e7d32',
    colorBorde: '#388e3c',
    categoria: 'sincategoria'
  },
  {
    id: 4,
    titulo: '¿En qué consiste la digitalización de procesos en la Gestión Pública en Perú?',
    descripcion: '16 de mayo de 2025 / No Comments',
    descripcion2: 'La digitalización de procesos en la gestión pública peruana consiste en integrar tecnologías para transformar trámites y servicios administrativos en formatos digitales, mejorando eficiencia, transparencia...',
    descripcionExtra: 'para garantizar que se cumplan los estándares de calidad, seguridad y sostenibilidad. Los profesionales en este campo deben coordinar recursos, gestionar presupuestos y cumplir con normativas legales.',
    imagen: '/img/digital1.png',
    colorFondo: '#e8f5e9',
    colorTexto: '#2e7d32',
    colorBorde: '#43a047',
    categoria: 'educacion'
  },
  {
    id: 5,
    titulo: 'Importancia de la Ética e Integridad en la Gestión Pública',
    descripcion: '16 de mayo de 2025 / No Comments',
    descripcion2: 'La ética e integridad en la gestión pública son fundamentales para construir confianza entre ciudadanos y gobernantes, garantizando transparencia, rendición de cuentas y respeto a...',
    descripcionExtra: 'para garantizar que se cumplan los estándares de calidad, seguridad y sostenibilidad. Los profesionales en este campo deben coordinar recursos, gestionar presupuestos y cumplir con normativas legales.',
    imagen: '/img/digital1.png',
    colorFondo: '#e3f2fd',
    colorTexto: '#1565c0',
    colorBorde: '#42a5f5',
    categoria: 'educacion'
  },
  {
    id: 6,
    titulo: 'EDUCACIÓN EJECUTIVA EN GESTION PÚBLICA - IGC',
    descripcion: '16 de mayo de 2025 / No Comments',
    descripcion2: 'La Educación Ejecutiva en Gestión Pública y Sistemas Administrativos se centra en proporcionar habilidades prácticas y estrategias directamente aplicables al entorno laboral. Este enfoque está...',
    descripcionExtra: 'para garantizar que se cumplan los estándares de calidad, seguridad y sostenibilidad. Los profesionales en este campo deben coordinar recursos, gestionar presupuestos y cumplir con normativas legales.',
    imagen: '/img/digital1.png',
    colorFondo: '#fff3e0',
    colorTexto: '#ef6c00',
    colorBorde: '#ffa726',
    categoria: 'educacion'
  },
  {
    id: 7,
    titulo: 'FINANZAS PÚBLICAS',
    descripcion: '16 de mayo de 2025 / No Comments',
    descripcion2: 'Las finanzas públicas gestionan estratégicamente los recursos del Estado para garantizar un uso eficiente y transparente en beneficio social. Incluyen la planificación del presupuesto, la...',
    descripcionExtra: 'para garantizar que se cumplan los estándares de calidad, seguridad y sostenibilidad. Los profesionales en este campo deben coordinar recursos, gestionar presupuestos y cumplir con normativas legales.',
    imagen: '/img/digital1.png',
    colorFondo: '#e8f5e9',
    colorTexto: '#2e7d32',
    colorBorde: '#66bb6a',
    categoria: 'innovacion'
  },
  {
    id: 8,
    titulo: 'SISTEMA DE PRESUPUESTO PÚBLICO',
    descripcion: '16 de mayo de 2025 / No Comments',
    descripcion2: 'El presupuesto público es vital para planificar y distribuir los recursos del gobierno, reflejando sus prioridades y asegurando transparencia. Incluye ingresos, principalmente de impuestos, y...',
    descripcionExtra: 'para garantizar que se cumplan los estándares de calidad, seguridad y sostenibilidad. Los profesionales en este campo deben coordinar recursos, gestionar presupuestos y cumplir con normativas legales.',
    imagen: '/img/digital1.png',
    colorFondo: '#e8f5e9',
    colorTexto: '#2e7d32',
    colorBorde: '#81c784',
    categoria: 'sincategoria'
  },
  {
    id: 9,
    titulo: 'SISTEMA DE TESORERÍA',
    descripcion: '16 de mayo de 2025 / No Comments',
    descripcion2: 'El Sistema de Tesorería Pública asegura el uso eficiente y responsable de los fondos del Estado, bajo principios como la Unidad de Caja y economicidad....',
    descripcionExtra: 'para garantizar que se cumplan los estándares de calidad, seguridad y sostenibilidad. Los profesionales en este campo deben coordinar recursos, gestionar presupuestos y cumplir con normativas legales.',
    imagen: '/img/digital1.png',
    colorFondo: '#e3f2fd',
    colorTexto: '#1565c0',
    colorBorde: '#64b5f6',
    categoria: 'innovacion'
  },
  {
    id: 10,
    titulo: 'SISTEMA DE ENDEUDAMIENTO PÚBLICO',
    descripcion: '16 de mayo de 2025 / No Comments',
    descripcion2: 'El Sistema Nacional de Endeudamiento Público es un conjunto integral de órganos, instituciones, normas y procesos que tiene como propósito garantizar una gestión eficiente y...',
    descripcionExtra: 'para garantizar que se cumplan los estándares de calidad, seguridad y sostenibilidad. Los profesionales en este campo deben coordinar recursos, gestionar presupuestos y cumplir con normativas legales.',
    imagen: '/img/digital1.png',
    colorFondo: '#fff3e0',
    colorTexto: '#ef6c00',
    colorBorde: '#ffb74d',
    categoria: 'sincategoria'
  },
  {
    id: 11,
    titulo: 'SISTEMA DE CONTABILIDAD',
    descripcion: '16 de mayo de 2025 / No Comments',
    descripcion2: 'El Sistema de Contabilidad Pública es clave para una gestión fiscal transparente y eficiente. Regido por el Decreto Legislativo N.º 1438 y supervisado por la...',
    descripcionExtra: 'para garantizar que se cumplan los estándares de calidad, seguridad y sostenibilidad. Los profesionales en este campo deben coordinar recursos, gestionar presupuestos y cumplir con normativas legales.',
    imagen: '/img/digital1.png',
    colorFondo: '#e8f5e9',
    colorTexto: '#2e7d32',
    colorBorde: '#388e3c',
    categoria: 'sincategoria'
  },
  {
    id: 12,
    titulo: 'SISTEMAS ELECTRÓNICOS DE GESTIÓN PÚBLICA',
    descripcion: '16 de mayo de 2025 / No Comments',
    descripcion2: 'Los sistemas SIGA, SIAF y SEACE modernizan la gestión pública mediante tecnología que mejora la eficiencia, transparencia y control de recursos. Permiten tomar decisiones estratégicas,...',
    descripcionExtra: 'para garantizar que se cumplan los estándares de calidad, seguridad y sostenibilidad. Los profesionales en este campo deben coordinar recursos, gestionar presupuestos y cumplir con normativas legales.',
    imagen: '/img/digital1.png',
    colorFondo: '#e8f5e9',
    colorTexto: '#2e7d32',
    colorBorde: '#43a047',
    categoria: 'innovacion'
  },
  {
    id: 13,
    titulo: 'SISTEMA NACIONAL DE ABASTECIMIENTO (SNA)',
    descripcion: '16 de mayo de 2025 / No Comments',
    descripcion2: 'El Sistema Nacional de Abastecimiento Público garantiza una provisión eficiente de bienes, servicios y obras en el sector estatal. Abarca desde contrataciones hasta la gestión...',
    descripcionExtra: 'para garantizar que se cumplan los estándares de calidad, seguridad y sostenibilidad. Los profesionales en este campo deben coordinar recursos, gestionar presupuestos y cumplir con normativas legales.',
    imagen: '/img/digital1.png',
    colorFondo: '#e3f2fd',
    colorTexto: '#1565c0',
    colorBorde: '#1976d2',
    categoria: 'sincategoria'
  },
  {
    id: 14,
    titulo: 'SISTEMA ADMINISTRATIVO DE GESTIÓN DE RECURSOS HUMANOS – SAGRH',
    descripcion: '16 de mayo de 2025 / No Comments',
    descripcion2: 'La modernización de la administración pública peruana exige una gestión eficiente del talento humano. El Sistema de Gestión de Recursos Humanos, liderado por SERVIR, abarca...',
    descripcionExtra: 'para garantizar que se cumplan los estándares de calidad, seguridad y sostenibilidad. Los profesionales en este campo deben coordinar recursos, gestionar presupuestos y cumplir con normativas legales.',
    imagen: '/img/digital1.png',
    colorFondo: '#fff3e0',
    colorTexto: '#ef6c00',
    colorBorde: '#ff9800',
    categoria: 'sincategoria'
  },
  {
    id: 15,
    titulo: 'DERECHO ADMINISTRATIVO PÚBLICO',
    descripcion: '16 de mayo de 2025 / No Comments',
    descripcion2: 'El Derecho Administrativo regula el funcionamiento del Estado y su relación con los ciudadanos, asegurando legalidad, transparencia y eficiencia en la gestión pública. Su marco...',
    descripcionExtra: 'para garantizar que se cumplan los estándares de calidad, seguridad y sostenibilidad. Los profesionales en este campo deben coordinar recursos, gestionar presupuestos y cumplir con normativas legales.',
    imagen: '/img/digital1.png',
    colorFondo: '#e8f5e9',
    colorTexto: '#2e7d32',
    colorBorde: '#388e3c',
    categoria: 'educacion'
  },
  {
    id: 16,
    titulo: 'SISTEMA DE CONTROL GUBERNAMENTAL',
    descripcion: '16 de mayo de 2025 / No Comments',
    descripcion2: 'El control gubernamental es clave para garantizar el buen uso de los recursos públicos y el cumplimiento de políticas del Estado. La Contraloría General de...',
    descripcionExtra: 'para garantizar que se cumplan los estándares de calidad, seguridad y sostenibilidad. Los profesionales en este campo deben coordinar recursos, gestionar presupuestos y cumplir con normativas legales.',
    imagen: '/img/digital1.png',
    colorFondo: '#e3f2fd',
    colorTexto: '#1565c0',
    colorBorde: '#42a5f5',
    categoria: 'innovacion'
  },
  {
    id: 17,
    titulo: 'SISTEMA DE MODERNIZACIÓN DE LA GESTIÓN PÚBLICA',
    descripcion: '16 de mayo de 2025 / No Comments',
    descripcion2: 'La Ley N.º 27658 impulsa la modernización de la gestión pública en el Perú, buscando una administración más eficiente, orientada al ciudadano y basada en...',
    descripcionExtra: 'para garantizar que se cumplan los estándares de calidad, seguridad y sostenibilidad. Los profesionales en este campo deben coordinar recursos, gestionar presupuestos y cumplir con normativas legales.',
    imagen: '/img/digital1.png',
    colorFondo: '#fff3e0',
    colorTexto: '#ef6c00',
    colorBorde: '#ffa726',
    categoria: 'innovacion'
  },
  {
    id: 18,
    titulo: 'HABILIDADES BLANDAS',
    descripcion: '16 de mayo de 2025 / No Comments',
    descripcion2: 'Las habilidades blandas son competencias interpersonales fundamentales para el éxito personal y profesional. Entre ellas destacan la comunicación, empatía, trabajo en equipo, liderazgo, adaptabilidad y...',
    descripcionExtra: 'para garantizar que se cumplan los estándares de calidad, seguridad y sostenibilidad. Los profesionales en este campo deben coordinar recursos, gestionar presupuestos y cumplir con normativas legales.',
    imagen: '/img/digital1.png',
    colorFondo: '#e8f5e9',
    colorTexto: '#2e7d32',
    colorBorde: '#66bb6a',
    categoria: 'educacion'
  }
];

export default posts;